# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: 井戸端マザーハウス
email: idobata.mother@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  井戸端マザーハウスはこういう感じです。
  なんとか。
baseurl: "" # the subpath of your site, e.g. /blog
url:              http://site.idobata.house

twitter_username: KazueKaraduman



# ----------- CONFIGURABLE START -----------
signoff:            "kazue" # Your name
signoff_message:    "また来てね！"
# facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-56175514-6
share:            true # Turn on twitter and facebook share buttons

links:
  - name:         報告
    url:          /
    external:     false
  - name:         ホーム
    url:          /home.html
    external:     false
  - name:         ブログ
    url:          http://idobata-mother.hatenablog.com/
    external:     true
  - name:         井戸端マザーハウスについて
    url:          /about.html
    external:     false
  - name:         アクセス
    url:          /access.html
    external:     false
  - name:         売店
    url:          /shop.html
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title.html
defaults:
  - values:
      layout: "default"



# Build settings
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed
  - jekyll-assets
#  - jekyll-slim

slim:
  pretty: true
  format: html5

assets:
  sources:
    - _assets/images

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
